name: newsapplication
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - images/Vector.png
    - images/maldives.png
    - images/woman.png
    - images/hongkong.png
    - images/woman2.png
    - images/Trending.png
    - images/play.png
    - images/see.png
    - images/china.png
    - images/prof.png
    - images/fav.png
    - images/home.png
    - images/notif.png
    - images/line.png
    - images/beach.png
    - images/star.png
    - images/back1.png
    - images/addFav.png
    - images/keanu.png
    - images/elly.png
    - images/ukraine.png
    - images/iran.png
    - images/calendar.png
    - images/time.png
    - images/cut.png
    - images/church.png
  
  
